### ISSUE TITLE
ITVR Task - Application Status Change Feature

### ISSUE THREAD

**Issue by shayjeff** [bcgov/itvr#692]
**Describe the task**
Develop a feature in the ITVR system allowing business area personnel to change the status of an application from "redeemed" to "approved".

**Purpose**
Enable the business area to independently manage application the status change (redeem to approved) and reducing reliance on the development team and promoting agility in processing requests.

**Acceptance Criteria**
- [ ] Business area users can access and update application statuses
- [ ] Proper access controls are in place for status changes. 

**Additional context**
- Provide user training.
- Need role-based access controls for security.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/692?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by tim738745** [comment]
@emi-hi yes, I think it's going to be a button in the django console. If it were me, I would make it like the "verify/decline" buttons on the right side of the page when a console user is deciding whether to verify or decline a submitted application, but maybe @shayjeff wants to see if Kailee can do a wireframe for this?

Also, just to clarify, this only applies to redeemed, non-legacy applications, and the code will also need to:
(1) change the "redeemed" flag of the associated go_electric_rebate object to false, and
(2) update the NCDA's list when the user clicks "Back to Approved" (or whatever we end up calling the button) so that its "Status" field is "Not-Redeemed"

**Comment by shayjeff** [comment]
@emi-hi, I can see if Kailee can do a wireframe, if that would help.

**Comment by shayjeff** [comment]
Tested with Tim and the users.
