### ISSUE TITLE
ITVR - Feature Development: Extending Rebate Approval Expiry

### ISSUE THREAD

**Issue by shayjeff** [bcgov/itvr#698]
**Task Description**
Create a feature to allow business area users the ability to extend approval expiry dates for rebates, beyond the default 15 days to accommodate requests for 30-day extensions. 

**Purpose**
The task aims to provide flexibility to the business area, enabling timely action on approval requests. This will streamline the approval process, reducing dependency on the development team for manual adjustments.

**Acceptance Criteria**
- [ ] Business area users can extend approval expiry dates in the system.
- [ ] The system accurately updates the application approval expiry date to reflect the extension to 30 days.

**Development Checklist**
(1) Make a new proxy model and ModelAdmin class (see admin.py) that gets the expired applications, and implement the "extend" functionality (recreate the go_electric_rebate with a user-entered rebate amount + change statuses + update the record in the NCDA's list) ; we'll probably also need additional HTML templates (see api/templates).

**Additional context**
- There has been an increase in demand to have applications extended for 30 days. 
- The current system automatically extends approvals by 15 days, which no longer seems to meet business needs.
- Requests for late submissions, such as missed reimbursement applications due to expired approvals, highlight the necessity for extending approval expiry beyond the default period.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/698?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by tim738745** [comment]
@shayjeff I made it so that console users can, for each expired application, select a rebate amount ($1000, $2000, or $4000) and make it so that: 
(1) The application has a status of "approved", 
(2) The rebate associated with the application is recreated with the selected amount and sent over to the NCDA with a status of "Not_Redeemed", and 
(3) The new rebate's expiry date is 30 days after the date of their extension action
Could you please check with the business area if this is okay? We can also do another quick meeting with them to go over this! Thanks!

**Comment by shayjeff** [comment]
Tested with BA
